[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lexflow"
authors = [{name = "Fuad", email = "issa.fuad@gmail.com"}]
dynamic = ["version", "description"]
